### ISSUE TITLE
Unsupported config option for services.app: 'dns_opt'

### ISSUE THREAD

**Issue by georgringer** [mblaschke/TYPO3-docker-boilerplate#177] opened 2017-04-23 17:05 UTC
After a clean checkout of dev branch I get

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.app: 'dns_opt'
```

symlinking the `docker-compose.development.yml`

**Comment by mblaschke** [comment] 2017-04-23 21:37
Can you post `docker version` and `docker-compose version`?

**Comment by georgringer** [comment] 2017-04-24 03:35
```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   b9f10c9
 Built:        Thu Jun  2 03:53:12 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64
```

```
docker-compose version 1.7.1, build unknown
docker-py version: 1.8.1
CPython version: 2.7.10
OpenSSL version: OpenSSL 0.9.8zh 14 Jan 2016
```

**Comment by mblaschke** [comment] 2017-04-24 07:12
Please update your docker and/or docker-compose.
There was a change in one of the last versions.

**Comment by mblaschke** [comment] 2017-04-24 22:50
This lines seems to be needed for newer docker version so please either update your environment or just remove it.
Sorry :(

**Comment by mblaschke** [comment] 2017-04-30 10:55
Was removed because.
Was added to fix an issue but it seems the issue is gone (temporary issue?!)

Anyway we can close this.

**Closed as completed by mblaschke** 2017-04-30 10:55 UTC
